const shuffledArray = array => array.slice().sort(() => 0.5 - Math.random());

let casualCards = [
    { id: 1, type: '1', iconType: 'fas', icon: 'anchor', flip: false, finished: false },
    { id: 2, type: '1', iconType: 'fas', icon: 'anchor', flip: false, finished: false },
    { id: 3, type: '2', iconType: 'fab', icon: 'angellist', flip: false, finished: false },
    { id: 4, type: '2', iconType: 'fab', icon: 'angellist', flip: false, finished: false },
    { id: 5, type: '3', iconType: 'fas', icon: 'apple-alt', flip: false, finished: false },
    { id: 6, type: '3', iconType: 'fas', icon: 'apple-alt', flip: false, finished: false },
    { id: 7, type: '4', iconType: 'fas', icon: 'angry', flip: false, finished: false },
    { id: 8, type: '4', iconType: 'fas', icon: 'angry', flip: false, finished: false },
    { id: 9, type: '5', iconType: 'fas', icon: 'atom', flip: false, finished: false },
    { id: 10, type: '5', iconType: 'fas', icon: 'atom', flip: false, finished: false },
    { id: 11, type: '6', iconType: 'fas', icon: 'atlas', flip: false, finished: false },
    { id: 12, type: '6', iconType: 'fas', icon: 'atlas', flip: false, finished: false },
    { id: 13, type: '7', iconType: 'fas', icon: 'award', flip: false, finished: false },
    { id: 14, type: '7', iconType: 'fas', icon: 'award', flip: false, finished: false },
    { id: 15, type: '8', iconType: 'fas', icon: 'balance-scale', flip: false, finished: false },
    { id: 16, type: '8', iconType: 'fas', icon: 'balance-scale', flip: false, finished: false },
];

let mediumCards = [
    { id: 1, type: '1', iconType: 'fas', icon: 'anchor', flip: false, finished: false },
    { id: 2, type: '1', iconType: 'fas', icon: 'anchor', flip: false, finished: false },
    { id: 3, type: '2', iconType: 'fab', icon: 'angellist', flip: false, finished: false },
    { id: 4, type: '2', iconType: 'fab', icon: 'angellist', flip: false, finished: false },
    { id: 5, type: '3', iconType: 'fas', icon: 'apple-alt', flip: false, finished: false },
    { id: 6, type: '3', iconType: 'fas', icon: 'apple-alt', flip: false, finished: false },
    { id: 7, type: '4', iconType: 'fas', icon: 'angry', flip: false, finished: false },
    { id: 8, type: '4', iconType: 'fas', icon: 'angry', flip: false, finished: false },
    { id: 9, type: '5', iconType: 'fas', icon: 'atom', flip: false, finished: false },
    { id: 10, type: '5', iconType: 'fas', icon: 'atom', flip: false, finished: false },
    { id: 11, type: '6', iconType: 'fas', icon: 'atlas', flip: false, finished: false },
    { id: 12, type: '6', iconType: 'fas', icon: 'atlas', flip: false, finished: false },
    { id: 13, type: '7', iconType: 'fas', icon: 'award', flip: false, finished: false },
    { id: 14, type: '7', iconType: 'fas', icon: 'award', flip: false, finished: false },
    { id: 15, type: '8', iconType: 'fas', icon: 'balance-scale', flip: false, finished: false },
    { id: 16, type: '8', iconType: 'fas', icon: 'balance-scale', flip: false, finished: false },
    { id: 17, type: '9', iconType: 'fas', icon: 'adjust', flip: false, finished: false },
    { id: 18, type: '9', iconType: 'fas', icon: 'adjust', flip: false, finished: false },
    { id: 19, type: '10', iconType: 'fab', icon: 'artstation', flip: false, finished: false },
    { id: 20, type: '10', iconType: 'fab', icon: 'artstation', flip: false, finished: false },
    { id: 21, type: '11', iconType: 'fas', icon: 'asterisk', flip: false, finished: false },
    { id: 22, type: '11', iconType: 'fas', icon: 'asterisk', flip: false, finished: false },
    { id: 23, type: '12', iconType: 'fab', icon: 'atlassian', flip: false, finished: false },
    { id: 24, type: '12', iconType: 'fab', icon: 'atlassian', flip: false, finished: false },
    { id: 25, type: '13', iconType: 'fas', icon: 'baby', flip: false, finished: false },
    { id: 26, type: '13', iconType: 'fas', icon: 'baby', flip: false, finished: false },
    { id: 27, type: '14', iconType: 'fas', icon: 'baby-carriage', flip: false, finished: false },
    { id: 28, type: '14', iconType: 'fas', icon: 'baby-carriage', flip: false, finished: false },
    { id: 29, type: '15', iconType: 'fas', icon: 'bacteria', flip: false, finished: false },
    { id: 30, type: '15', iconType: 'fas', icon: 'bacteria', flip: false, finished: false },
    { id: 31, type: '16', iconType: 'fas', icon: 'bahai', flip: false, finished: false },
    { id: 32, type: '16', iconType: 'fas', icon: 'bahai', flip: false, finished: false },
    { id: 33, type: '17', iconType: 'fas', icon: 'band-aid', flip: false, finished: false },
    { id: 34, type: '17', iconType: 'fas', icon: 'band-aid', flip: false, finished: false },
    { id: 35, type: '18', iconType: 'fab', icon: 'bandcamp', flip: false, finished: false },
    { id: 36, type: '18', iconType: 'fab', icon: 'bandcamp', flip: false, finished: false },
];

let hardCards = [
    { id: 1, type: '1', iconType: 'fas', icon: 'anchor', flip: false, finished: false },
    { id: 2, type: '1', iconType: 'fas', icon: 'anchor', flip: false, finished: false },
    { id: 3, type: '2', iconType: 'fab', icon: 'angellist', flip: false, finished: false },
    { id: 4, type: '2', iconType: 'fab', icon: 'angellist', flip: false, finished: false },
    { id: 5, type: '3', iconType: 'fas', icon: 'apple-alt', flip: false, finished: false },
    { id: 6, type: '3', iconType: 'fas', icon: 'apple-alt', flip: false, finished: false },
    { id: 7, type: '4', iconType: 'fas', icon: 'angry', flip: false, finished: false },
    { id: 8, type: '4', iconType: 'fas', icon: 'angry', flip: false, finished: false },
    { id: 9, type: '5', iconType: 'fas', icon: 'atom', flip: false, finished: false },
    { id: 10, type: '5', iconType: 'fas', icon: 'atom', flip: false, finished: false },
    { id: 11, type: '6', iconType: 'fas', icon: 'atlas', flip: false, finished: false },
    { id: 12, type: '6', iconType: 'fas', icon: 'atlas', flip: false, finished: false },
    { id: 13, type: '7', iconType: 'fas', icon: 'award', flip: false, finished: false },
    { id: 14, type: '7', iconType: 'fas', icon: 'award', flip: false, finished: false },
    { id: 15, type: '8', iconType: 'fas', icon: 'balance-scale', flip: false, finished: false },
    { id: 16, type: '8', iconType: 'fas', icon: 'balance-scale', flip: false, finished: false },
    { id: 17, type: '9', iconType: 'fas', icon: 'adjust', flip: false, finished: false },
    { id: 18, type: '9', iconType: 'fas', icon: 'adjust', flip: false, finished: false },
    { id: 19, type: '10', iconType: 'fab', icon: 'artstation', flip: false, finished: false },
    { id: 20, type: '10', iconType: 'fab', icon: 'artstation', flip: false, finished: false },
    { id: 21, type: '11', iconType: 'fas', icon: 'asterisk', flip: false, finished: false },
    { id: 22, type: '11', iconType: 'fas', icon: 'asterisk', flip: false, finished: false },
    { id: 23, type: '12', iconType: 'fab', icon: 'atlassian', flip: false, finished: false },
    { id: 24, type: '12', iconType: 'fab', icon: 'atlassian', flip: false, finished: false },
    { id: 25, type: '13', iconType: 'fas', icon: 'baby', flip: false, finished: false },
    { id: 26, type: '13', iconType: 'fas', icon: 'baby', flip: false, finished: false },
    { id: 27, type: '14', iconType: 'fas', icon: 'baby-carriage', flip: false, finished: false },
    { id: 28, type: '14', iconType: 'fas', icon: 'baby-carriage', flip: false, finished: false },
    { id: 29, type: '15', iconType: 'fas', icon: 'bacteria', flip: false, finished: false },
    { id: 30, type: '15', iconType: 'fas', icon: 'bacteria', flip: false, finished: false },
    { id: 31, type: '16', iconType: 'fas', icon: 'bahai', flip: false, finished: false },
    { id: 32, type: '16', iconType: 'fas', icon: 'bahai', flip: false, finished: false },
    { id: 33, type: '17', iconType: 'fas', icon: 'band-aid', flip: false, finished: false },
    { id: 34, type: '17', iconType: 'fas', icon: 'band-aid', flip: false, finished: false },
    { id: 35, type: '18', iconType: 'fab', icon: 'bandcamp', flip: false, finished: false },
    { id: 36, type: '18', iconType: 'fab', icon: 'bandcamp', flip: false, finished: false },
    { id: 37, type: '19', iconType: 'fas', icon: 'baseball-ball', flip: false, finished: false },
    { id: 38, type: '19', iconType: 'fas', icon: 'baseball-ball', flip: false, finished: false },
    { id: 39, type: '20', iconType: 'fas', icon: 'battery-full', flip: false, finished: false },
    { id: 40, type: '20', iconType: 'fas', icon: 'battery-full', flip: false, finished: false },
    { id: 41, type: '21', iconType: 'fas', icon: 'bath', flip: false, finished: false },
    { id: 42, type: '21', iconType: 'fas', icon: 'bath', flip: false, finished: false },
    { id: 43, type: '22', iconType: 'fas', icon: 'bicycle', flip: false, finished: false },
    { id: 44, type: '22', iconType: 'fas', icon: 'bicycle', flip: false, finished: false },
    { id: 45, type: '23', iconType: 'fas', icon: 'binoculars', flip: false, finished: false },
    { id: 46, type: '23', iconType: 'fas', icon: 'binoculars', flip: false, finished: false },
    { id: 47, type: '24', iconType: 'fas', icon: 'blender', flip: false, finished: false },
    { id: 48, type: '24', iconType: 'fas', icon: 'blender', flip: false, finished: false },
    { id: 49, type: '25', iconType: 'fas', icon: 'beer', flip: false, finished: false },
    { id: 50, type: '25', iconType: 'fas', icon: 'beer', flip: false, finished: false },
    { id: 51, type: '26', iconType: 'fab', icon: 'bitcoin', flip: false, finished: false },
    { id: 52, type: '26', iconType: 'fab', icon: 'bitcoin', flip: false, finished: false },
    { id: 53, type: '27', iconType: 'fas', icon: 'bomb', flip: false, finished: false },
    { id: 54, type: '27', iconType: 'fas', icon: 'bomb', flip: false, finished: false },
    { id: 55, type: '28', iconType: 'fas', icon: 'bong', flip: false, finished: false },
    { id: 56, type: '28', iconType: 'fas', icon: 'bong', flip: false, finished: false },
    { id: 57, type: '29', iconType: 'fas', icon: 'bone', flip: false, finished: false },
    { id: 58, type: '29', iconType: 'fas', icon: 'bone', flip: false, finished: false },
    { id: 59, type: '30', iconType: 'fas', icon: 'bolt', flip: false, finished: false },
    { id: 60, type: '30', iconType: 'fas', icon: 'bolt', flip: false, finished: false },
    { id: 61, type: '31', iconType: 'fas', icon: 'bowling-ball', flip: false, finished: false },
    { id: 62, type: '31', iconType: 'fas', icon: 'bowling-ball', flip: false, finished: false },
    { id: 63, type: '32', iconType: 'fas', icon: 'brain', flip: false, finished: false },
    { id: 64, type: '32', iconType: 'fas', icon: 'brain', flip: false, finished: false },
];


export let shuffledCasual = shuffledArray(casualCards);
export let shuffledMedium = shuffledArray(mediumCards);
export let shuffledHard = shuffledArray(hardCards);